index = "paras"
prefix = "/Users/bhavya/Documents/explanation/UI"
corpus = "file.toml"
dataset = "idx_data_heading"

[query-runner]
timeout = 120
query-path = "slides-queries.txt"
query-id-start = 0

[[analyzers]]
ngram = 1
method = "ngram-word"

[[analyzers.filter]]
type = "icu-tokenizer"

[[analyzers.filter]]
type = "lowercase"